batch_size:
  desc: null
  value: 64
data_sampler:
  desc: null
  value: random_class
dataset:
  desc: null
  value: cars196
decay:
  desc: null
  value: 0
embed_dim:
  desc: null
  value: 384
eval_start:
  desc: null
  value: 35
feature_dropout:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0005
lr_cosine_min:
  desc: null
  value: 1.0e-06
lr_proxy:
  desc: null
  value: 0.01
mix_precision:
  desc: null
  value: true
n_epochs:
  desc: null
  value: 50
num_p_prompt:
  desc: null
  value: 50
num_prompt:
  desc: null
  value: 80
optim:
  desc: null
  value: adamw
p_prompt_depth:
  desc: null
  value: 8
prompt_block_step:
  desc: null
  value: 2
prompt_depth:
  desc: null
  value: 11
prompt_p_block_step:
  desc: null
  value: 2
proxy_bias_ratio:
  desc: null
  value: 0.7
proxy_data_range:
  desc: null
  value: both_all
proxy_mix_bias:
  desc: null
  value: true
proxy_net_head:
  desc: null
  value: isolated
rnn_dropout:
  desc: null
  value: 0
same_p_scheduler:
  desc: null
  value: true
samples_per_class:
  desc: null
  value: 2
scheduler:
  desc: null
  value: cosine
semantic_mix_type:
  desc: null
  value: gru_relu
vit_bitfit:
  desc: null
  value: true
vit_head:
  desc: null
  value: true
vit_prompt:
  desc: null
  value: true
vit_proxy_net:
  desc: null
  value: true
no_train_metrics:
  desc: null
  value: true