batch_size:
  desc: null
  value: 64
data_sampler:
  desc: null
  value: random_class
dataset:
  desc: null
  value: cub200
decay:
  desc: null
  value: 1.0e-06
embed_dim:
  desc: null
  value: 512
eval_start:
  desc: null
  value: 30
feature_dropout:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.001
lr_cosine_length:
  desc: null
  value: 100
lr_cosine_min:
  desc: null
  value: 1.0e-07
lr_proxy:
  desc: null
  value: 0.01
mix_precision:
  desc: null
  value: true
n_epochs:
  desc: null
  value: 60
negative_push:
  desc: null
  value: partially
normal:
  desc: null
  value: true
num_p_prompt:
  desc: null
  value: 5
num_prompt:
  desc: null
  value: 20
optim:
  desc: null
  value: sgd
p_prompt_depth:
  desc: null
  value: 4
pretrained_model:
  desc: null
  value: vit_base_patch16_224_in21k
prompt_block_step:
  desc: null
  value: 0
prompt_depth:
  desc: null
  value: 12
prompt_p_block_step:
  desc: null
  value: 5
proxy_bias_ratio:
  desc: null
  value: 0.4
proxy_data_range:
  desc: null
  value: both_all
proxy_mix_bias:
  desc: null
  value: true
proxy_net_head:
  desc: null
  value: isolated
rnn_dropout:
  desc: null
  value: 0
same_p_scheduler:
  desc: null
  value: true
samples_per_class:
  desc: null
  value: 2
scheduler:
  desc: null
  value: cosine
semantic_mix_type:
  desc: null
  value: gru_relu
vit_bitfit:
  desc: null
  value: true
vit_head:
  desc: null
  value: true
vit_prompt:
  desc: null
  value: true
vit_proxy_net:
  desc: null
  value: true
no_train_metrics:
  desc: null
  value: true